import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));
const pages={
 home:{ko:['생각을 바꾸는 작은 노트','TRIZ 발명원리와 과학적 효과를 배우고, 새로운 문제 해결의 관점을 발견하세요.',[
 ['40가지 발명원리','원리와 사례를 살펴보고 나의 생각을 메모하세요. 학습 완료 기록과 저장 목록을 계정에 연결해 이어갈 수 있습니다.'],
 ['Effects · 원리를 눈으로 이해하기','장비 이미지, 단계별 도식과 설명으로 과학적 효과와 응용 기술의 작동 과정을 알아봅니다.'],
 ['한 번 더 깊이 생각하기','모순, 분리 원리, 표준해와 시스템 진화를 통해 문제를 다른 관점에서 탐구합니다.'],
 ['연간 구독','기본 요금은 US$5 / 년입니다. 실제 금액·통화·세금 및 이용 가능한 상품은 App Store 또는 Google Play 구매 화면을 확인하세요. 상세 학습 콘텐츠 이용에는 활성 구독이 필요합니다.'],
 ['계정과 데이터','이메일 또는 지원되는 소셜 로그인으로 계정을 이용합니다. 개인정보 처리, 구독 조건과 계정 삭제 방법은 아래 정책에서 확인할 수 있습니다.']]],
 en:['A small note. A different perspective.','Explore TRIZ inventive principles and scientific effects to discover new approaches to problem solving.',[
 ['40 inventive principles','Explore principles and examples, save notes and continue with account-linked learning progress and bookmarks.'],
 ['Effects · See how it works','Equipment images, step-by-step diagrams and explanations illustrate scientific effects and applied technologies.'],
 ['Go deeper','Explore contradictions, separation principles, standard solutions and system evolution.'],
 ['Annual subscription','The base price is US$5 per year. Available products, actual prices, currency and taxes are shown in the App Store or Google Play purchase screen. Detailed learning content requires an active subscription.'],
 ['Your account and data','Use email or supported social sign-in. Read the policies below for privacy, subscription conditions and account deletion.']]]},
 terms:{ko:['서비스 이용약관','TRIZ Note를 안전하고 공정하게 이용하기 위한 기준입니다.',[
 ['1. 목적과 서비스','TeraGraph(이하 “운영자”)는 TRIZ Note를 통해 발명원리, Effects, 문제 해결 학습 및 기록 기능을 제공합니다. 교육용 설명·도식·장비 이미지는 전문 설계, 안전 검증이나 법률·특허 자문을 대신하지 않습니다. 실제 실험·장비 제작에는 별도의 전문 검토와 안전 조치가 필요합니다.'],
 ['2. 계정 이용','본인의 계정과 정확한 정보를 사용하고 인증정보를 안전하게 관리해야 합니다. 타인 사칭, 계정 도용·양도, 인증 또는 구독 제한 우회, 비정상적인 자동 수집과 서비스 방해를 금지합니다. 계정 도용이 의심되면 고객지원으로 알려주세요.'],
 ['3. 유료 구독','기본 상품은 1년 단위 자동 갱신 구독이며 기준 요금은 US$5 / 년입니다. 실제 판매 가격·통화·세금·기간·혜택은 결제 전 스토어 화면에 표시된 내용이 우선합니다. 결제는 Apple 또는 Google 계정으로 처리됩니다. 구독 중 제공되는 상세 학습 콘텐츠와 신규 자료를 이용할 수 있으며, 제공 범위의 중요한 변경은 사전에 안내합니다.'],
 ['4. 갱신·해지·환불','구독은 해지하지 않으면 스토어 조건에 따라 자동 갱신됩니다. 다음 갱신을 원하지 않으면 현재 기간 종료 최소 24시간 전에 해당 스토어의 구독 관리에서 해지해 주세요. 해지 후에는 이미 결제한 기간까지 이용할 수 있습니다. 앱 삭제나 계정 삭제만으로 스토어 구독이 해지되지 않습니다. 환불·청약철회는 해당 스토어 절차와 적용 법령에 따르며, 법정 권리를 제한하지 않습니다.'],
 ['5. 콘텐츠와 이용자 메모','앱의 콘텐츠·이미지·소프트웨어 권리는 운영자 또는 정당한 권리자에게 있습니다. 개인 학습을 위한 이용 범위를 넘어 무단 복제·배포·재판매하지 마세요. 이용자 메모의 권리는 이용자에게 있으며, 운영자는 저장·동기화 등 서비스 제공에 필요한 범위에서만 처리합니다. 타인의 개인정보나 권리를 침해하는 내용을 입력하지 마세요.'],
 ['6. 서비스 변경과 이용 제한','점검, 장애 또는 보안상 사유로 서비스가 일시 중단될 수 있으며 가능한 경우 사전 안내합니다. 위반이 확인되면 사유와 정도에 따라 이용을 제한하고 이의제기 경로를 제공합니다. 긴급한 보안 위험에는 우선 조치 후 안내할 수 있습니다. 유료 서비스의 중대한 축소·종료 시 이용자 보호와 적용 법령에 따른 조치를 안내합니다.'],
 ['7. 계정 삭제','설정의 계정 삭제 또는 고객지원 요청으로 탈퇴할 수 있습니다. 본인 확인 후 계정과 연결된 서버 학습 기록·메모·저장 목록이 삭제되며 복구되지 않을 수 있습니다. 자세한 범위와 제한은 개인정보처리방침 및 계정 삭제 안내를 확인하세요.'],
 ['8. 책임과 분쟁','운영자는 관련 법령에 따른 책임을 부담합니다. 본 약관은 고의·중과실에 대한 책임이나 이용자의 강행법상 권리를 배제하지 않습니다. 분쟁은 우선 고객지원으로 협의하며, 해결되지 않으면 적용 법령과 관할 규정에 따릅니다.'],
 ['9. 변경 및 문의','중요한 약관 변경은 시행 전 앱 또는 웹페이지를 통해 내용과 시행 시점을 안내합니다. 이용자에게 불리하거나 중요한 권리 변경에는 필요한 사전 안내·동의 절차를 진행합니다. 문의 및 이용 제한 이의제기: manager@teragraph.io.']]],
 en:['Terms of service','Rules for using TRIZ Note safely and fairly.',[
 ['1. Service','TeraGraph provides TRIZ Note for learning inventive principles, scientific effects and problem-solving methods, with personal learning records. Educational diagrams and equipment illustrations do not replace professional design, safety validation or legal/patent advice. Real experiments and construction require appropriate expert review and safety measures.'],
 ['2. Accounts','Use your own account and accurate information, and protect your credentials. Impersonation, account theft or transfer, bypassing authentication or subscription controls, abusive automated collection and service disruption are prohibited. Contact support if you suspect unauthorized access.'],
 ['3. Subscription','The base product is an automatically renewing annual subscription at a reference price of US$5 per year. The store purchase screen controls actual pricing, currency, taxes, duration and benefits. Apple or Google processes payment. Subscription access covers available detailed learning content and new materials during the paid period. Material benefit changes will be communicated in advance.'],
 ['4. Renewal, cancellation and refunds','Subscriptions renew under the relevant store terms unless cancelled. Cancel through your store at least 24 hours before the current period ends to avoid the next renewal. Access normally continues through the paid period. Deleting the app or your account does not cancel a store subscription. Refunds and withdrawal rights follow the relevant store process and applicable law; statutory rights are not waived.'],
 ['5. Content and notes','App content, images and software belong to TeraGraph or their respective rights holders. Do not reproduce, redistribute or resell them beyond permitted personal learning use. You retain rights to your notes; we process them as needed to store and synchronize them. Do not enter content that infringes others’ privacy or rights.'],
 ['6. Availability and restrictions','Maintenance, outages or security events may interrupt service. We provide advance notice where possible. Violations may result in proportionate restrictions with reasons and an appeal route; urgent security action may precede notice. Material reductions or termination of paid services will be handled with notice and protections required by applicable law.'],
 ['7. Account deletion','Request deletion in Settings or through support. After identity verification, your account and associated cloud learning records, notes and bookmarks are deleted and may not be recoverable. See the privacy and deletion pages for details.'],
 ['8. Responsibility and disputes','TeraGraph remains responsible as required by applicable law. These terms do not exclude liability for intentional misconduct or gross negligence, or mandatory consumer rights. Contact support first to resolve disputes; applicable law and jurisdiction rules govern unresolved matters.'],
 ['9. Changes and contact','Material changes will be announced in the app or website before they take effect, with any notice or consent required for changes affecting your rights. Questions and appeals: manager@teragraph.io.']]]},
 privacy:{ko:['개인정보처리방침','어떤 정보를 왜 처리하는지 안내합니다.',[
 ['1. 운영자와 문의','TRIZ Note의 운영자는 TeraGraph입니다. 개인정보 열람·정정·삭제·처리 제한 및 문의는 manager@teragraph.io로 요청할 수 있습니다. 요청 처리에 필요한 범위에서 본인 확인을 진행합니다.'],
 ['2. 계정·인증 정보','이메일 가입 시 이메일 주소와 인증정보를 Supabase Auth를 통해 처리합니다. Google 로그인 시 Google 계정 식별자, 이메일 및 제공되는 기본 프로필(이름·프로필 이미지 등)을 인증 목적으로 처리할 수 있습니다. Google 비밀번호는 앱이 받지 않습니다. 로그인 세션은 기기의 보안 저장소에서 관리합니다.'],
 ['3. 학습·구독 정보','저장한 원리, 학습 완료 기록, 입력한 메모와 계정 식별자를 저장·동기화합니다. 언어 등 설정과 일부 학습 자료는 기기에 저장될 수 있습니다. 구독 확인에는 스토어 종류, 상품·거래 식별자, 유효기간 및 이용권 상태를 처리합니다. 카드번호 등 결제수단 정보는 Apple·Google이 처리하며 앱 서버에 직접 저장하지 않습니다.'],
 ['4. 처리 목적','계정 인증, 학습 기록 저장·동기화, 구독 이용권 확인, 콘텐츠 제공, 장애·부정 이용 대응 및 고객 문의 처리에 사용합니다. 지원 요청 시 이용자가 보낸 이메일·문의 내용도 처리합니다. 비밀번호, 결제 카드번호, 신분증 등 불필요한 민감정보를 문의에 보내지 마세요.'],
 ['5. 처리 서비스와 국외 처리','Supabase는 대한민국 서울 리전에서 인증·데이터베이스·콘텐츠 저장을 제공합니다. Google은 Google 로그인과 이 공개 웹페이지 호스팅을, Apple·Google은 각 스토어 결제와 구독 관리를 제공합니다. Google 로그인 시 이용자가 선택한 계정의 식별자·이메일·기본 프로필이 암호화된 네트워크를 통해 로그인 시 전송됩니다. Google·Apple은 글로벌 인프라에서 정보를 처리할 수 있으며, 각 사업자의 개인정보처리방침과 계약상 보호조치가 적용됩니다. 앱의 계정·학습 데이터 기본 저장 위치는 Supabase 서울 리전입니다.'],
 ['6. 보유와 삭제','계정·학습 기록·메모·저장 목록·이용권 연결 정보는 계정 이용 중 보유하며, 계정 삭제가 완료되면 활성 서버 데이터에서 삭제합니다. 보안·장애 대응 로그는 생성 후 최대 90일, 고객지원 문의는 처리 완료 후 최대 3년 보관한 뒤 삭제합니다. 백업에 남은 삭제 데이터는 통상 30일 이내 순환 삭제됩니다. 다만 관계 법령상 별도 보관 의무가 있는 항목은 해당 기간 동안 분리 보관할 수 있습니다. 스토어 거래 기록은 Apple·Google 정책과 법적 의무에 따릅니다.'],
 ['7. 권리와 계정 삭제','설정 → 계정 삭제에서 요청하거나 지원 이메일로 연락할 수 있습니다. Google 전용 계정 등 앱 내 본인 확인이 어려운 경우 이메일 경로를 이용해 주세요. 계정·서버 메모·학습 기록·저장 목록의 삭제는 되돌릴 수 없습니다. 기기 자료와 캐시는 로그아웃·앱 삭제 등으로 별도 정리할 수 있습니다. 구독은 스토어에서 별도 해지해야 합니다.'],
 ['8. 웹페이지와 보호 조치','이 공개 사이트에는 별도 로그인, 광고 추적기 또는 분석 도구를 넣지 않았습니다. 호스팅 제공자는 페이지 제공과 보안을 위해 접속 정보를 처리할 수 있습니다. 앱은 HTTPS 통신, 기기 보안 저장소 및 계정별 데이터 접근 제한을 사용합니다. 어떠한 보안 조치도 절대적인 안전을 보장하지는 않습니다.'],
 ['9. 아동·변경 안내','TRIZ Note는 만 14세 미만 아동을 대상으로 설계되지 않았으며, 만 14세 미만 이용자의 개인정보를 알게 된 경우 확인 후 삭제합니다. 처리 내용이 변경되면 이 페이지와 필요한 앱 안내를 갱신합니다. 중요한 변경은 시행 전에 알립니다. 시행일: 2026년 9월 26일.']]],
 en:['Privacy policy','What we process and why.',[
 ['1. Operator and contact','TRIZ Note is operated by TeraGraph. Contact manager@teragraph.io to request access, correction, deletion or restriction, or ask privacy questions. We may verify identity to the extent needed to process a request.'],
 ['2. Account and authentication','Email registration processes your email and authentication credentials through Supabase Auth. Google sign-in may provide your Google account identifier, email and basic profile such as name and profile image for authentication. The app does not receive your Google password. Login sessions are managed in device secure storage.'],
 ['3. Learning and subscription data','We store and synchronize bookmarks, completion records, notes and account identifiers. Preferences such as language and some learning materials may remain on the device. Subscription verification processes store, product and transaction identifiers, expiry and entitlement status. Apple or Google processes payment methods; our app server does not directly store card numbers.'],
 ['4. Purposes','Data supports authentication, learning synchronization, entitlement checks, content delivery, troubleshooting, abuse prevention and support. Support correspondence includes the email and information you send. Do not send passwords, card numbers, identity documents or unnecessary sensitive information.'],
 ['5. Providers and international processing','Supabase provides authentication, databases and content storage in its Seoul, South Korea region. Google provides Google sign-in and hosts this public website. Apple and Google manage their respective store payments and subscriptions. When you use Google sign-in, your selected account identifier, email and basic profile are transmitted over encrypted connections at sign-in. Google and Apple may process information on global infrastructure under their privacy policies and contractual safeguards. Core app account and learning data are stored in the Supabase Seoul region.'],
 ['6. Retention and deletion','Account data, learning records, notes, bookmarks and entitlement associations are retained while the account is active and removed from active server data when deletion completes. Security and troubleshooting logs are kept for up to 90 days, support correspondence for up to three years after resolution, and deleted data in rotating backups ordinarily for no more than 30 days. Records required by law may be isolated for the required period. Store transaction records follow Apple or Google policies and legal obligations.'],
 ['7. Your rights and account deletion','Use Settings → Delete account or contact support. Google-only accounts or users unable to complete in-app identity checks can use email support. Account and cloud note, progress and bookmark deletion cannot be reversed. Device data and caches may require separate clearing, logout or app removal. Cancel subscriptions separately in the relevant store.'],
 ['8. Website and safeguards','This website has no additional sign-in, advertising trackers or analytics tools. Hosting providers may process request data for delivery and security. The app uses HTTPS, device secure storage and account-based data access controls. No safeguards guarantee absolute security.'],
 ['9. Children and updates','TRIZ Note is not designed for children under 14. If we learn that we hold personal data from a child under 14, we will verify and delete it. We update this page and any required app notices when processing changes, and provide advance notice of material changes. Effective date: September 26, 2026.']]]},
 support:{ko:['고객지원','사용 중 불편한 점이나 계정 관련 요청을 보내주세요.',[
 ['문의하기','manager@teragraph.io · TeraGraph TRIZ Note 운영팀. 앱 버전, iOS·Android 버전, 문제가 발생한 화면과 재현 순서를 알려주세요. 스크린샷에는 개인정보나 결제정보가 포함되지 않도록 확인해 주세요.'],
 ['구독 관리','앱 설정의 구독 관리 또는 App Store·Google Play의 구독 메뉴에서 갱신·해지를 관리합니다. 환불은 결제한 스토어의 지원 절차를 이용하세요. 이메일로 카드번호나 비밀번호를 보내지 마세요.'],
 ['계정 삭제와 개인정보 요청','앱을 사용할 수 없어도 지원 이메일로 요청할 수 있습니다. 계정에 연결된 이메일에서 “TRIZ Note 계정 삭제 요청”이라는 제목으로 보내주세요. 요청한 계정의 소유 여부를 확인한 후 안내하며, Google 비밀번호를 요구하지 않습니다. 자세한 삭제 범위는 계정 삭제 안내를 확인하세요.']]],
 en:['Support','Get help with TRIZ Note and your account.',[
 ['Contact us','manager@teragraph.io · TeraGraph TRIZ Note support. Include your app version, iOS or Android version, affected screen and steps to reproduce the problem. Remove personal and payment information from screenshots.'],
 ['Manage subscriptions','Use subscription management in app settings or your App Store/Google Play account. Request refunds through the store where you paid. Never email card numbers or passwords.'],
 ['Deletion and privacy requests','You can email support even without access to the app. Send “TRIZ Note account deletion request” from the email associated with your account. We verify account ownership before processing and never ask for your Google password. See the deletion page for scope.']]]},
 deletion:{ko:['계정 삭제 안내','계정 삭제와 구독 해지는 서로 다른 절차입니다.',[
 ['앱에서 요청','설정 → 계정 삭제에서 안내되는 확인 절차를 진행하세요. Google 전용 계정처럼 앱 내 확인 절차를 완료할 수 없는 경우 아래 이메일 경로를 사용하세요.'],
 ['앱 없이 요청','계정에 연결된 이메일로 manager@teragraph.io에 “TRIZ Note 계정 삭제 요청”을 보내주세요. 비밀번호나 신분증을 보내지 마세요. 운영팀이 계정 소유 확인에 필요한 최소 정보와 후속 절차를 안내합니다.'],
 ['삭제되는 정보','계정 및 해당 계정에 연결된 서버 메모, 학습 완료 기록, 저장 목록과 이용권 연결 정보가 삭제 대상입니다. 삭제된 학습 기록은 복구할 수 없습니다. 기기에 남은 캐시·로컬 자료는 별도로 삭제해야 할 수 있습니다.'],
 ['삭제와 별개로 관리되는 정보','App Store·Google Play 거래 기록은 각 스토어가 관리합니다. 계정 삭제는 자동 갱신 구독을 해지하지 않으므로 먼저 스토어에서 해지해 주세요. 보안·장애 대응 로그는 최대 90일, 순환 백업은 통상 최대 30일, 고객지원 문의는 처리 완료 후 최대 3년 보관될 수 있으며 법정 보관 의무가 있는 기록은 해당 기간 동안 분리 보관됩니다.']]],
 en:['Delete your account','Deleting an account and cancelling a subscription are separate actions.',[
 ['Request in the app','Open Settings → Delete account and complete verification. If you cannot complete the in-app checks, including for Google-only accounts, use the email route below.'],
 ['Request without the app','Email manager@teragraph.io from your account email with the subject “TRIZ Note account deletion request”. Do not send passwords or identity documents. Support will explain the minimum verification and next steps.'],
 ['Data covered','Deletion covers your account and associated cloud notes, completion records, bookmarks and entitlement associations. Deleted learning records cannot be recovered. Device caches and local materials may need separate removal.'],
 ['Separate records','App Store and Google Play retain records under their own policies. Account deletion does not stop subscription renewals: cancel in the store first. Security and troubleshooting logs may be retained for up to 90 days, rotating backups ordinarily for up to 30 days, and support correspondence for up to three years after resolution. Legally required records may be isolated for the required period.']]]}
};
const labels={ko:['소개','이용약관','개인정보','고객지원','계정 삭제'],en:['About','Terms','Privacy','Support','Delete account']};
for(const lang of ['ko','en'])for(const [key,p] of Object.entries(pages)){
 const [title,lead,sections]=p[lang]; const base=lang==='en'?'/en':''; const route=k=>`${base}/${k==='home'?'':k+'.html'}`;
 const nav=Object.keys(pages).map((k,i)=>`<a ${k===key?'aria-current="page"':''} href="${route(k)}">${labels[lang][i]}</a>`).join('');
 const content=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${lead}"><title>${title} · TRIZ Note</title><link rel="icon" href="/logo.png"><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#main">${lang==='ko'?'본문으로':'Skip to content'}</a><header><a class="brand" href="${route('home')}"><img src="/logo.png" alt="" width="48" height="48">TRIZ <span>NOTE</span></a><a lang="${lang==='ko'?'en':'ko'}" href="${lang==='ko'?'/en':''}/${key==='home'?'':key+'.html'}">${lang==='ko'?'English':'한국어'}</a></header><div class="layout"><nav aria-label="${lang==='ko'?'페이지':'Pages'}">${nav}</nav><main id="main"><p class="eyebrow">TRIZ NOTE / ${key.toUpperCase()}</p><h1>${title}</h1><p class="lead">${lead}</p><aside class="notice">${lang==='ko'?'시행일 · 2026년 9월 26일':'Effective · September 26, 2026'}</aside>${sections.map(([h,b])=>`<section><h2>${h}</h2><p>${b}</p></section>`).join('')}<div class="contact"><strong>TeraGraph · TRIZ Note</strong><br><a href="mailto:manager@teragraph.io">manager@teragraph.io</a></div></main></div><footer>© 2026 TeraGraph · TRIZ Note</footer></body></html>`;
 const dir=`${root}public/${lang==='en'?'en/':''}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}${key==='home'?'index':key}.html`,content);
}
await copyFile(`${root}../assets/triz-note-brain-mark-v1.png`,`${root}public/logo.png`);
console.log('Generated 10 Korean/English production pages.');
