import { readdir, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const map = [];
for (const dir of ['principle-icons', 'illustrations', 'advanced', 'effects', 'localized']) {
  for (const file of (await readdir(new URL(`assets/content/${dir}/`, root))).sort()) {
    if (!/\.(png|jpg|jpeg|webp)$/i.test(file)) continue;
    map.push(`  ${JSON.stringify(`/assets/${dir}/${file}`)}: require(${JSON.stringify(`../../assets/content/${dir}/${file}`)}),`);
  }
}
await writeFile(new URL('src/data/assets.ts', root), `// Generated by scripts/generate-assets.mjs. Static Metro imports.\nimport type { ImageSourcePropType } from 'react-native';\nexport const assets: Record<string, ImageSourcePropType> = {\n${map.join('\n')}\n};\n`);
console.log(`Registered ${map.length} bundled native images.`);
